---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: image
  label: image
- type: text
  name: type
  label: type
- type: text
  name: project_url
  label: project_url
- type: list
  name: categories
  label: categories
- type: text
  name: description
  label: description
