---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog
- type: directory
  path: site/content/blog
  label: Post
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Portfolio
- type: directory
  path: site/content/portfolio
  label: Project
  create: all
  match: "**/*"
  exclude: _*
- type: heading
  label: Data
- type: document
  path: site/data/homepage.yml
  label: Homepage
- type: document
  path: site/content/about/_index.md
  label: About
- type: heading
  label: Configuration
- type: document
  path: site/config.toml
  label: Configuration
upload_dir: site/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.98.0
  preview_output_directory: site/public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: cd site && hugo server -D -E -F --port 8080 --bind 0.0.0.0
    --renderToDisk -d public
version: 0.98.0
